version: '3.8'
services:
  authorizationDatabase:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_pass
    ports:
      - '5432:5432'
    volumes: 
      - authorizationDatabase:/var/lib/postgresql/data
volumes:
  authorizationDatabase:
    driver: local